services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/var/www/html
      - /app/vendor
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - db
    networks:
      - myapp_network

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    ports:
      - "8000:80" # On accède à l'API via http://localhost:8000
    volumes:
      - ./backend:/var/www/html # Partage le même code source
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - myapp_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: myapp_frontend_nuxt
  #   ports:
  #     - "3000:3000" # On accède au site via http://localhost:3000
  #   volumes:
  #     - ./frontend:/app # Monte le code source pour le live-reload
  #     - /app/node_modules # S'assure que node_modules n'est pas écrasé
  #   environment:
  #     # Important pour que Nuxt puisse se lancer dans cet environnement
  #     NUXT_HOST: 0.0.0.0
  #     NUXT_PORT: 3000
  #   networks:
  #     - myapp_network

  # === Service Base de Données PostgreSQL ===
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Changez ce mot de passe !
    ports:
      - "5432:5432" # Permet de se connecter à la DB depuis l'extérieur (ex: DBeaver)
    volumes:
      - db_data:/var/lib/postgresql/data # Persistance des données
    networks:
      - myapp_network

# Définition du réseau partagé
networks:
  myapp_network:
    driver: bridge

# Définition du volume nommé pour la persistance
volumes:
  db_data: