server {
    listen 80;
    server_name kickdeal.site;

    # On définit le resolver DNS interne de Docker.
    # C'est la clé pour que Nginx puisse trouver les autres services.
    resolver 127.0.0.11 valid=30s;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        # On utilise une variable pour le nom du service.
        # Cela force Nginx à utiliser le resolver et à être plus patient.
        set $fastcgi_pass backend:9000;
        fastcgi_pass $fastcgi_pass;

        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        # internal; # Commenté pour le débogage si nécessaire
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}