-- 004_create_savings.sql
CREATE TABLE IF NOT EXISTS savings (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  rate INTEGER NOT NULL,
  balance INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
