export type AppError = {
  code: string;
  message?: string;
};

export const appError = (code: string, message?: string): AppError => ({ code, message });

export const SavingErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SAVING_PRODUCT_NOT_FOUND: 'SAVING_PRODUCT_NOT_FOUND',
  INITIAL_AMOUNT_BELOW_MIN: 'INITIAL_AMOUNT_BELOW_MIN',
  SOURCE_ACCOUNT_NOT_FOUND: 'SOURCE_ACCOUNT_NOT_FOUND',
  UNAUTHORIZED_SOURCE_ACCOUNT: 'UNAUTHORIZED_SOURCE_ACCOUNT',
  INSUFFICIENT_SOURCE_BALANCE: 'INSUFFICIENT_SOURCE_BALANCE',
  SAVING_ALREADY_EXISTS: 'SAVING_ALREADY_EXISTS',
  IBAN_GENERATION_FAILED: 'IBAN_GENERATION_FAILED',
  IBAN_INVALID: 'IBAN_INVALID',
  DEBIT_SOURCE_FAILED: 'DEBIT_SOURCE_FAILED',
  TRANSACTION_SAVE_FAILED: 'TRANSACTION_SAVE_FAILED',
  SAVING_NOT_FOUND: 'SAVING_NOT_FOUND',
  UNAUTHORIZED_SAVING_ACCOUNT: 'UNAUTHORIZED_SAVING_ACCOUNT',
  TARGET_ACCOUNT_NOT_FOUND: 'TARGET_ACCOUNT_NOT_FOUND',
  UNAUTHORIZED_TARGET_ACCOUNT: 'UNAUTHORIZED_TARGET_ACCOUNT',
  DEBIT_SAVING_FAILED: 'DEBIT_SAVING_FAILED',
  CREDIT_BANK_FAILED: 'CREDIT_BANK_FAILED',
  CREDIT_SAVING_FAILED: 'CREDIT_SAVING_FAILED',
  DEBIT_BANK_FAILED: 'DEBIT_BANK_FAILED',
  DEPOSIT_ERROR: 'DEPOSIT_ERROR',
  TRANSFER_ERROR: 'TRANSFER_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type SavingErrorCode = typeof SavingErrorCodes[keyof typeof SavingErrorCodes];
