import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/AppHeader";
import AuthProvider from "@/context/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className="min-w-screen min-h-screen flex flex-col overflow-x-hidden"
      >
        <AuthProvider>
          <AppHeader />
          <main className="flex-1 w-full relative">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
